### ISSUE TITLE
Usage and suggestions

### ISSUE THREAD

**Issue by zeffii** [zeffii/TubeTool#10]
This reflects the current state of the add-on, changes and enhancements can be introduced if suitable.

For now, the script assumes you select two faces on the same object. Why? because that's the scenario the script was written for. If you are trying to select two faces on two separate objects  (but both selected) then at present that doesn't work. A way to get around that issue is to duplicate + separate the faces and then join them into one object.
1. Face 1 -> shift+D (to duplicate the face) -> P -> separate selection
2. Face 2 -> shift+D -> P -> separate selection
3. Select both new face 'objects' and Ctrl+J to join them.
4. Then with the resulting object in edit mode, select the faces and invoke the tool.

In future it could place a tube between two selected faces on different objects, it totally makes sense to allow that.

**Comment by hertfordkc** [comment]
Seems like everything  I try to do in Blender has some quirk.  I was redirected here from stack exchange and I think this will take care of my problem.  Your last comment is right on.

**Comment by zeffii** [comment]
Hopefully the rest will be plain sailing. I think you were trying to use two separate face objects, the add-on expects an Object in _Edit Mode_ with two faces selected. I've described how to do that, but will find time to implement the alternative (two objects, two selected faces)

**Comment by hertfordkc** [comment]
That worked!  Do you anticipate adapting this so that the shape of Face 1 morphs into Face 2?

**Comment by zeffii** [comment]
what kind of shapes? If they have widely varying vertex counts, then NO. bluntly.  but otherwise... it's very possible.. most of the hard work is done already by the curve.

**Comment by zeffii** [comment]
for instance: these would be easy enough to morph: 
![image](https://cloud.githubusercontent.com/assets/619340/7784346/0f50b37e-0163-11e5-8cfb-7318cfc2b894.png)
but this wouldn't 
![image](https://cloud.githubusercontent.com/assets/619340/7784348/3a6eb394-0163-11e5-9017-96319fd85ccb.png)

**Comment by zeffii** [comment]
but this would, because vertex counts match:
![image](https://cloud.githubusercontent.com/assets/619340/7784354/8550426a-0163-11e5-9a05-f4342a48e7a4.png)

**Comment by hertfordkc** [comment]
I was thinking of simple scaling of faces with the same number of vertices, but your example would be awesome.

**Comment by zeffii** [comment]
I see, I hadn't yet implemented morph + twist, it was literally for generating tubes. If you hit F6 after triggering the addon there are plenty of details that can be tweaked (in case you missed that)

**Comment by zeffii** [comment]
sadly my computer is having RAM issues and it has become very unstable, i'm waiting for new ram. could take a while.

**Comment by hertfordkc** [comment]
What you've done so far is an enormous help  for me.  Thank you.  
Expanding to morph and twist would be nirvana.
