### ISSUE TITLE
Spiro curves

### ISSUE THREAD

**Issue by brothermechanic** [zeffii/TubeTool#14]
Hello
I try your tube script, its very good!
Do you know about Spiro curves in Inscape? http://i.imgur.com/DPOBRxp.png
This is a fantastic tool for ideal curve shapes, but 2d only... 
Can you create same "Spiro" curve shape formula? It will make your script great!

**Comment by zeffii** [comment]
Hi @brothermechanic   nope, i don't know SpiroCurves.

No i can't create the same spiro for you :) sorry!

**Comment by brothermechanic** [comment]
Not only for me)
Sadly
