### ISSUE TITLE
problem on blender-2.79-git

### ISSUE THREAD

**Issue by brothermechanic** [zeffii/TubeTool#15]
Hello
Super addon, thank you.
Can you update addon to latest blender-2.79 from buildbot or git?
This error happent on run Add Simple Tube command.
```
Traceback (most recent call last):
  File "/usr/share/blender/2.79/scripts/addons/TubeTool-9999/tt_operators.py", line 316, in __init__
    curvedata.dimensions = '3D'
AttributeError: Writing to ID classes in this context is not allowed: TT_tube, Curve datablock, error setting Curve.dimensions

location: <unknown location>:-1
```

**Comment by zeffii** [comment]
yeah. , no problem.

**Comment by zeffii** [comment]
after reading the error message more carefully, i'll certainly have a look, but i'm not super sure how fast it will find a fix. @brothermechanic   -- thanks for the heads up anyway.

**Comment by zeffii** [comment]
maybe try https://github.com/zeffii/TubeTool/archive/nightly_patch.zip , but i suspect i'm too optimistic that that will work

**Comment by zeffii** [comment]
well, i've committed to master . it seems to suffice :)   https://github.com/zeffii/TubeTool/pull/16/files

**Comment by brothermechanic** [comment]
Works!
Thank you!

**Comment by zeffii** [comment]
cool, closing
