### ISSUE TITLE
add-on rewrite for 2.80+

### ISSUE THREAD

**Issue by zeffii** [zeffii/TubeTool#22]
> One thing I've noticed that you are probably already aware of... It seems you can only create one curve with the addon. It has been this way since the first 0.0.4 release of Tube Tool. I have found ways around this limitation for the time being and have been keeping a close eye on the addon, since it's my favorite from Blender 2.7-series
 If you try to create a second curve, it re-allocates your curve to that new selection of squares. Also if you make the curve into a mesh, the addon no longer works unless you restart Blender, it just throws an error. 
https://gyazo.com/88aaf68fdbda57101cfa5bf856d51023
This also happens if you delete the curve.

> Also the "to mesh" button throws an error right away in every case:
https://gyazo.com/968ccda3c7f92c7e6de84a604fecb1ac
The only way to get multiple curves in your project is to duplicate the curve every time you create a new one, so that when you run the addon again, it re-allocates your duplicated curve.
I've been keeping an eye on this addon for some time hoping that this gets worked out. I assume the current functionality is due to an incomplete API ?

_Originally posted by @toomanydemons in https://github.com/zeffii/TubeTool/issues/20#issuecomment-475392641_

- [ ] support fresh curves
- [x] fix to_mesh api call

**Comment by zeffii** [comment]
note to self: https://docs.blender.org/api/blender2.8/bpy.types.Operator.html?

**Comment by zeffii** [comment]
https://github.com/zeffii/TubeTool/pull/23 for the latest code

**Comment by zeffii** [comment]
let me know how this goes. https://github.com/zeffii/TubeTool/pull/23

it's a relatively lazy fix. there are remaining solutions..which i'd like to avoid :)

**Comment by toomanydemons** [comment]
Amazing!!!! OH god, I missed this addon... It WORKS!!! 💃 

Thanks so much for this. One of the most useful modeling tools. Second to none for pipes, wires, telephone lines, you name it. 🥇

**Comment by toomanydemons** [comment]
You know, you could probably sell a version of this addon that is more polished and has more options. If I saw it on blendermarket I would buy it immediately.

**Comment by zeffii** [comment]
unfortunately i can't commit to dealing with whatever the consequences would be of accepting money for the software.

i may still add improvements anyway, (from my own todo lists). But if you can shortlist some small improvements that I could make to add extra kick-ass-ness,  be my guest to suggest them in a new issue.
