### ISSUE TITLE
Blender 2.8

### ISSUE THREAD

**Issue by zeromold** [zeffii/TubeTool#26]
Does not function in 2.82.  Add tubing is greyed out and command not found in search.

**Comment by zeffii** [comment]
you must have two faces selected, (in one object), then "Add Tubing" becomes available in the W menu.

**Comment by zeromold** [comment]
Thank you. The key is 'in one object.'

**Comment by zeffii** [comment]
yep, but that's definitely an arbitrary limitation now..

**Comment by zeffii** [comment]
but i looked at the current code, at it will take more work than I feel like putting into it at the moment, to make that work on two separate objects.

**Comment by zeffii** [comment]
well. looks like i found time. it works on separate objects now too.
