### ISSUE TITLE
undocumented operator? TubeTool does not work

### ISSUE THREAD

**Issue by ghost** [zeffii/TubeTool#28]
Hi, I am using 2.83 and following information shown for tubetool
![2020-08-08 22_14_39-Blender_  D__Work_3D_Space Chopper Body 1 blend](https://user-images.githubusercontent.com/46490254/89719087-f37b8f80-d9c4-11ea-937e-f481a2c95845.png)

**Comment by zeffii** [comment]
you must first select two, (and only two) faces. then execute the operator.

**Comment by zeffii** [comment]
i've added a docstring to the operator. Thanks for reporting it.
https://github.com/zeffii/TubeTool/pull/29/files
