### ISSUE TITLE
Feature request: add tubing between vertices

### ISSUE THREAD

**Issue by loopkin** [zeffii/TubeTool#30]
It would be great!
Your addon is already awesome!
Thanks :-)

**Comment by zeffii** [comment]
how would the normal be decided?

**Comment by loopkin** [comment]
Haha good point! I didn't think about that...
I don't know if it's possible to average the normals of the faces around the vertice?
Anyway your addon is awesome, thanks!

**Comment by zeffii** [comment]
yes, averaging the surrounding faces would produce a normal.

unfortunately i'm not super likely to get around to that feature soon. but i'll remember it..for a day when i'm really bored or waiting for something.

**Comment by loopkin** [comment]
Ahah I understand! Not a problem :-)
Maybe one day... but I wish you not to be really bored!

**Comment by zeffii** [comment]
try the latest release. @loopkin

**Comment by loopkin** [comment]
@zeffii I've tested it, it works well!!!
Well done, congratulation!
Thanks :-)

**Comment by zeffii** [comment]
a little explanation maybe.

to establish the startup `radius` and `scale` values it uses the `average edge length` of edges connected to each selected vertex, and divides that by two. This feels somewhat natural but over time maybe real-world distance between points can be used to tweak the start `normal` so the control points of the bezier are a bit more predictable.

let me know.

**Comment by loopkin** [comment]
@zeffii I think that the startup value for radius is great!

For the startup size of the handles (I'm not sure to understand well what you mean), but yes, it might be better if the startup size of the handles could somehow be proportional to the distance between the start and end of the tube.

**Comment by loopkin** [comment]
@zeffii I think I found kind of a bug:
When 2 objects are selected if I select 2 elements on the same object and try to add a tube, I get an alert:
`if two objects are selected, then select one face on each object`
From there it's impossible to add any tube whatever I try...

**Comment by loopkin** [comment]
@zeffii Also when I click on Tube Callback, Blender crashes...
Not a big deal, fantastic work 👍

**Comment by zeffii** [comment]
when you click on "Tube Callback" ? where

**Comment by zeffii** [comment]
>  When 2 objects are selected if I select 2 elements on the same object and try to add a tube, I get an alert:

hmmm, yeah it expects the selections to be on two different objects, if multiple objects are selected. I have no testing code implemented to defend against that.

**Comment by loopkin** [comment]
> > When 2 objects are selected if I select 2 elements on the same object and try to add a tube, I get an alert:
> 
> hmmm, yeah it expects the selections to be on two different objects, if multiple objects are selected. I have no testing code implemented to defend against that.

This is not the problem... the problem is that from there it is impossible to have Tube Tool working anymore at all.
I have to quit and reopen Blender to make it work again.

**Comment by loopkin** [comment]
> when you click on "Tube Callback" ? where

Here:
![Screenshot 2021-06-15 at 20 05 07](https://user-images.githubusercontent.com/10942332/122102355-a0107400-ce15-11eb-9654-ce803665524a.png)

**Comment by zeffii** [comment]
oh OK. i'll dig into that!  thanks for the report. The add-on should not crash blender. that's bad :)

**Comment by zeffii** [comment]
it may require a bit of a rewrite, i might not be able to get my head around the old code. The plumbing is at least 6 years old.

**Comment by loopkin** [comment]
> it may require a bit of a rewrite, i might not be able to get my head around the old code. The plumbing is at least 6 years old.

No problem, don't worry!
Your addon is already very handy :-)

**Comment by zeffii** [comment]
it's too hot to be outside, so i reworked some of the add-on internally.  https://github.com/zeffii/TubeTool/pull/34

**Comment by zeffii** [comment]
i think i've managed to fix the crashing of blender, there's no point where the add-on can reference non-existing objects.
but the bug you mentioned about two objects in edit mode, but only using the geometry of one object - is not yet addressed. but Should be supremely fixable :)

**Comment by loopkin** [comment]
@zeffii have you released a new version?

**Comment by zeffii** [comment]
not yet, but you can see the code changes in that link above
