### ISSUE TITLE
Works in Blender 2.8 but not in 2.9

### ISSUE THREAD

**Issue by KW71** [zeffii/TubeTool#31]
Hi! This addon is great, and a time saver!
I tried it on 2.80 and 2.83, and works fine. But doesn't work in 2.90 or 2.92  (when you type "Add Simple Tube" the option is no there... 
Is strange because if works for 2.83, in theory should work for 2.90, right? Any plans on updating your addon?

**Comment by zeffii** [comment]
https://github.com/zeffii/TubeTool/issues/28

**Comment by zeffii** [comment]
https://github.com/zeffii/TubeTool/issues/26

**Comment by KW71** [comment]
O.K. I see thanks.
It works in 2.9+ when used from the "W" menu. The thing is that such menu only exist if you have enabled right click selection.
I wonder why doesn't show up in the search window.
EDIT, EDIT!
Is in the menu when you right-click on the viewport... sorry for the troubles. Thanks again!

**Comment by zeffii** [comment]
: ) i try to keep the add-on working in recent blender releases. just in-case i need access to it . so i was a but surprised to get reports that people couldn't get it working.

....back to hibernation ...
