### ISSUE TITLE
problem with installation on 2.92

### ISSUE THREAD

**Issue by jessypinkmancristal** [zeffii/TubeTool#32]
hello, 
I got a problem I download the zip file and after I use the add on installer inside blender 
i selected the two file in the zip to proceed blender said to me that it was installed but I didn't find tube tool from the both All and community
I was on Mac Pro last version of the the iOS

If somebody can help me ?
Thanks

**Comment by jessypinkmancristal** [comment]
ok I got the solution my Mac unzip the file after the download I re zip the file and it works !

**Comment by zeffii** [comment]
good for you @jessypinkmancristal !
