### ISSUE TITLE
Blender 3.x Support

### ISSUE THREAD

**Issue by vmalloc** [zeffii/TubeTool#35]
Hi,

After installing on Blender 3.0.0, the addon won't activate properly (no "add tubing" menu at all), and a warning shows up claiming I should upgrade to Blender 2.82 🤷

**Comment by zeffii** [comment]
Thanks @vmalloc  i'll look into it.

**Comment by zeffii** [comment]
it does work here, no errors enabling.  You have to have to faces selected before triggering the operator. and W opens the menu.

**Comment by vmalloc** [comment]
Oh, apparently I downloaded the latest release instead of just the master branch... When I try with master it works as expected.... Perhaps it is worth creating a new official release to avoid confusion...

In any case sorry for the hassle, and thanks!

**Comment by zeffii** [comment]
ok :)
