### ISSUE TITLE
Stage 3

### ISSUE THREAD

**Issue by zeffii** [zeffii/TubeTool#4]
Some milestones for this stage
- [x] overall width scaling factor
- [x]  scale factor for first bezier point radius
- [x]  scale factor for last bezier point radius
- [x]  both extention handles have separate controls
- [x]  subdivisions over length of curve (resolution_u over active spline)
- [x]  subdivisions over profile (or choice to select profile)
- [x] view shade smooth
- [x] view object wires

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/7101328/834e857e-e054-11e4-8408-a818f8a0848a.png)

**Comment by toomanydemons** [comment]
epic :+1:  What else is there to add? It looks finished. It's a dream tool for Blender users.

**Comment by toomanydemons** [comment]
This plugin is something modelers will be using constantly. I'm glad you let me in on this. I've been hitting my head on the wall with Blender curves, but this makes it too easy. Blender is getting really fun to be in. I think i'll be abandoning Maya.

**Comment by zeffii** [comment]
I agree, I think i'm done on the features. Further coding UI results in diminishing returns for my time. I will add some sanity checks ( like avoid allowing it to be invoked if less or more than 2 faces are selected, and some pesky plumbing (which seems to work, but i'm not sure why)

**Comment by toomanydemons** [comment]
Excellent. Best tool ever. I wonder why no one did this sooner.

**Comment by zeffii** [comment]
hmm, i've noticed it doesn't reset parameters when you select two different new polygons.. this is a bug

there's also the issue of the modal code not running at all..may take time to get around to fixing

**Comment by toomanydemons** [comment]
no it's not a bug all the Blender tools are like that. They retain the information in the parameters on multiple uses of the tool, but only in the specific file. I like it actually. If I make a 16-face diameter UV sphere and decide to work in that resolution, it remembers later when I make another instance of that object. Creating objects for games, stuff like that is great.

**Comment by zeffii** [comment]
yep, I can understand why the current state would be useful, that's why I haven't changed it in `master` yet. I will leave it this way by default, and work towards adding a sub operator to reset a selection of parameters in one go.

I imagine that the polygons used for triggering the operator aren't often the right size anyway..

Either way, i'll have to leave it for now.
