### ISSUE TITLE
Stage 4

### ISSUE THREAD

**Issue by zeffii** [zeffii/TubeTool#5]
I would like to keep the amount of code to a minimum because that means less places for bugs to hide, but I would also like to at least have a way to indicate which end of the curve is point 1 .

As discussed in earlier issues, some options are: 
1. include some vicinity checking code, so the mouse cursor when over f.ex the first polygon and click-dragged could extend that handle (without leaving edit mode for the main object)
2. alternatively, draw greasepencil extender lines with two different colours to indicate ext_1 and ext_2 (colourblind friendly, or user definable)
3. go mental with BGL and BLF module (drawing custom openGL info)

**Comment by zeffii** [comment]
I added flip u / v to the `stage3d` branch, it's only minor .. not sure to push it to master.

**Comment by zeffii** [comment]
![janked_opt](https://cloud.githubusercontent.com/assets/619340/7106310/2c154322-e13c-11e4-8258-1b58b9c7d360.gif)

**Comment by toomanydemons** [comment]
Well thought-out. I'm definitely going to start learning some Python. I
have an idea for a plugin to export color maps for Substance
Painter/Quixel. I'm pretty sure it's going to take at least a few months to
handle Python in Blender, but from your work here, I can see it's all going
to be worth it.

I know you're probably sick of hearing it: This is the best tool ever.
Thank you.

**Comment by zeffii** [comment]
ok, iĺl commit this and then wash my hands on the whole affair :)

**Comment by zeffii** [comment]
there's a bug with zombie operators, each time you call the _add tube_ operator, it does not automatically end any existing _add tube_ operators, It's probably easy to fix, will find time tonight..

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/7122275/b1a52276-e21a-11e4-866e-9cbf6381330c.png)
the black dots, are for resetting the radius of that slider...  the code to do this is so ugly i will definitely not commit..(to master)  but it can be tested from the stage4_zppl branch

**Comment by toomanydemons** [comment]
Sounds like a good idea to fix, for the sake of speed. As i've been using
it, I simply convert to mesh after each.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/7134262/93ec81c6-e29b-11e4-8066-cdbea860dac3.png)
implemented on handles too. I thought I was finished, but one last thing i might add is a way to equalize the radii (equalize to : smallest | largest )

Most of the interesting (fun) code is now written, but dealing with the UI and having the operator remove itself when it's retriggered is proving a royal pain in the ass.

**Comment by zeffii** [comment]
image placement
![opt_turnpike](https://cloud.githubusercontent.com/assets/619340/7134921/f2a60376-e2a1-11e4-9db6-f68a4a2f4bc1.gif)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/7135094/b1d4d8ca-e2a3-11e4-8dfa-36d849451a04.png)

**Comment by zeffii** [comment]
of course, it's entirely possible to also describe the profile scale along the Curve path, by using a Taper Object. The taper object could be programatically generated too
- begin shape
- inbetween shape (bridge shape)
- number of repeats of bridge shape
- end shape (default mirror of begin shape)

**Comment by toomanydemons** [comment]
That is totally awesome. This tool is getting seriously amplified. I
thought it was good to go but apparently not. Looks great so far. You need
to upload this to some Blender addon sites, i'm sure a lot of people could
benefit from this.

**Comment by toomanydemons** [comment]
I mean, if you haven't already :)

**Comment by zeffii** [comment]
i'm OK with it staying obscure, but minds change..

**Comment by zeffii** [comment]
merged those props + reset value sliders. Incase I forget

**Comment by toomanydemons** [comment]
As you have it right now, the tool gives a very high lever of control
immediately to the user. I can create a curve even on faces aiming at a
different axis and adjust everything about them. How easy would it be to
include a 'convert to mesh' button? (for quickly adding groups of wires
bundled together which don't require curve subdivisions.

Another awesome idea (since you're getting detailed with this tool I
thought I would try to think of things you might like) is a subdivision for
the curve itself, adding points for further adjustment. As it stands you
still have to grab the curve, enter edit mode, grab both points, press w,
and subdivide. Making a button for this would be awesome.

But none of my ideas are necessary, just dressing. So far your tool for
piping is the best, I just thought I would try to help with ideas since
you're making it even more killer. :D I don't think there's much more you
can do with it. So far it's better than Maya and Max. Its only rival at
this point is Modo. (Modo has awesome native pipe-building tools where you
click along a path in top/front/side view and the pipe builds itself).

**Comment by toomanydemons** [comment]
which is saying a lot, since it's widely said that Modo currently has the
best modeling tools in the world. I think it does, but Blender is pretty
great.

**Comment by zeffii** [comment]
> How easy would it be to include a 'convert to mesh' button?   

easy enough. I had this in the back of my mind

>  a subdivision for the curve itself, adding points for further adjustment

With the curve in edit mode, all those operations like subdivide curve (W -> subdivide) you get out of the box. If i implemented that (not saying I wont...) then it has to be done from scratch using trigonometry to find the new point position and handle locations. (not a big deal.. just effort )
- setting the curve knots to selected can be automated, so whenever the user enters the curve edit mode a subdivision is w->subdiv
- alternatively, a way to jump to edit more and back out of...

I will think about these things.

**Comment by toomanydemons** [comment]
That is true, it's not much effort to subdivide the curve as it is. It's
also not much effort to convert the curve to a mesh. I was just scraping
the barrel. As I said, the tool as it stands is killer, there's not much
else that needs to be done.
