### ISSUE TITLE
stage 6

### ISSUE THREAD

**Issue by zeffii** [zeffii/TubeTool#7]
probably the most useful thing now is to put the first and last bezier point state to select=True, for the faster manual subdivide.

I'll have a think about dealing with autosubdivide, it starts to get complicated and I don't have time for that.

**Comment by toomanydemons** [comment]
No need for auto-subdivide. I must say you're getting crazy with this too.
It already works great! But this is your baby I can tell. :) It's still the
most useful Blender tool I have and probably will be for quite awhile
(until they do something for easier UV stacking lol).

**Comment by zeffii** [comment]
I implemented bezier handle drawing using GreasePencil, but it's a little jittery. Probably need to implement it in BGL instead 
![image](https://cloud.githubusercontent.com/assets/619340/7219632/e583f972-e6a8-11e4-9c2b-92ceb0e9d6df.png)

**Comment by zeffii** [comment]
I added bgl drawing instead:
![image](https://cloud.githubusercontent.com/assets/619340/7249640/1b0d9c3c-e81c-11e4-8be6-968e428420dc.png)
it's still a little wonky, but it will work better than the GP lines when complete

**Comment by mifth** [comment]
Hi.

this is good project.
I made somework with bezier in python.
You can check CurveStretch in MiraTools project.
https://github.com/mifth/mifthtools
http://blenderartists.org/forum/showthread.php?366107-MiraTools
![cache0](https://cloud.githubusercontent.com/assets/2251298/7251240/2acc2772-e832-11e4-89ad-3f7a2333a456.png)

For your project - i think it would be cool to make interactive tubes. To tweak the curve profile in realtime.

**Comment by zeffii** [comment]
Thanks for the suggestion @mifth. There are many ways to do this, but I find the control method of the sliders the most convenient. Also all the controls are in one place beside each-other. If the user wants fine control, switch to edit mode of the Curve.

**Comment by zeffii** [comment]
@mifth i think after all this time i finally understand what you said here, yeah it would be really neat to have more abstract control over the bezier beyond my simple offering. Hopefully if someone really wants it bad enough they will expend the energy to learn/apply python.
